version: '2'

services:
    shepherd:
        image: oldwebtoday/shepherd
        build: ./shepherd

        command: uwsgi uwsgi.ini --mount /=/shepherd/main.py

        environment:
            - REDIS_BROWSER_URL=redis://redis/0
            - CLUSTER_NAME=browser_shepherd
            - NETWORK_NAME=browsers_default
            - IDLE_TIMEOUT=60
            - AUDIO_TYPE=opus
            - CONTAINER_EXPIRE_SECS=1200

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        ports:
            - 9020:9020

    redis:
        image: redis:2.8.21


