version: '2'

services:
    shepherd-browsers:
        image: oldwebtoday/shepherd-browsers
        build: ./shepherd-browsers

        #command: uwsgi uwsgi.ini --mount /=/shepherd/main.py

        environment:
            - REDIS_BROWSER_URL=redis://redis/0
            - CLUSTER_NAME=browser_shepherd
            - NETWORK_NAME=browsers_default
            - IDLE_TIMEOUT=60
            - AUDIO_ALLOWED=true
            - CONTAINER_EXPIRE_SECS=1200

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        ports:
            - 9020:9020

    redis:
        image: redis:3.2.4


